[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
port = 8501
address = "localhost"
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = true
headless = true

[theme]
# Dark mode with professional color scheme
primaryColor = "#00D4AA"           # Cyan accent for buttons and highlights
backgroundColor = "#0E1117"        # Deep dark background
secondaryBackgroundColor = "#1E1E1E"  # Slightly lighter for cards
textColor = "#FAFAFA"             # High contrast white text
font = "sans serif"               # Clean modern font

[logger]
level = "error"

[client]
showErrorDetails = true
toolbarMode = "auto" 