# Environment Variables for IBKR Trading Dashboard

# Trading Environment (live_trading or paper_trading)  
IBIND_TRADING_ENV=live_trading

# Server Port (default: 8080)
PORT=8080

# Docker-specific (only needed for containerized deployment)
PYTHONPATH=/app